version: "3.10.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-practice-sqlserver
    encironment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}